/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

void calculadora_1(char *host, float numero1, float numero2, char operador)
{
	CLIENT *clnt;
	float *result;

	#ifndef DEBUG
		clnt = clnt_create(host, CALCULADORA, CALCULADORA1, "udp");
		if (clnt == NULL)
		{
			clnt_pcreateerror(host);
			exit(1);
		}
	#endif /* DEBUG */

	switch (operador)
	{
		case '+':
			result = sumar_1(numero1, numero2, clnt);
			break;

		case '-':
			result = restar_1(numero1, numero2, clnt);
			break;
		
		case 'x':
			result = multiplicar_1(numero1, numero2, clnt);
			break;
		
		case '/':
			result = dividir_1(numero1, numero2, clnt);
			break;
	}
	
	if (result == (float *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}

	printf("El resultado es: %f\n", *result);

	#ifndef DEBUG
		clnt_destroy(clnt);
	#endif /* DEBUG */
}

int existe(char operador, const char* operadores, int tam)
{
	int resultado = 0;

	for(int i = 0; i < tam && resultado == 0; i++)
		if(operadores[i] == operador)
			resultado = 1;
	
	return resultado;
}

int main(int argc, char *argv[])
{
	char *host;
	float numero1, numero2;
	char operador;
	const char operadores[4] = {'+', '-', 'x', '/'};

	if (argc != 5)
	{
		printf("Número de parámetros incorrecto\n");
		printf("Sintaxis: <programa> <servidor> <numero1> <operador> <numero2>\n");
		exit(1);
	}

	host = argv[1];
	numero1 = atof(argv[2]);
	operador = argv[3][0];
	numero2 = atof(argv[4]);

	if (existe(operador, operadores, 4) == 0)
	{
		printf("El operador introducido no es válido\n");
		exit(1);
	}

	calculadora_1(host, numero1, numero2, operador);
	exit(0);
}
