/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

float *
sumar_1_svc(float a, float b,  struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */

	result = a + b;

	return &result;
}

float *
restar_1_svc(float a, float b,  struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */

	result = a - b;

	return &result;
}

float *
multiplicar_1_svc(float a, float b,  struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */

	result = a * b;

	return &result;
}

float *
dividir_1_svc(float a, float b,  struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */

	result = a / b;

	return &result;
}
