/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"
#include <math.h>

float *
sumar_1_svc(float a, float b,  struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */
	result = a + b;
	return &result;
}

float *
restar_1_svc(float a, float b,  struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */
	result = a - b;
	return &result;
}

float *
multiplicar_1_svc(float a, float b,  struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */
	result = a * b;
	return &result;
}

float *
dividir_1_svc(float a, float b,  struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */
	result = a / b;
	return &result;
}

float *
seno_2_svc(float a,  struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */
	result = sin(a);
	return &result;
}

float *
coseno_2_svc(float a,  struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */
	result = cos(a);
	return &result;
}

float *
tangente_2_svc(float a,  struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */
	result = tan(a);
	return &result;
}

float *
arcoseno_3_svc(float a,  struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */
	result = asin(a);
	return &result;
}

float *
arcocoseno_3_svc(float a,  struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */
	result = acos(a);
	return &result;
}

float *
arcotangente_3_svc(float a,  struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */
	result = atan(a);
	return &result;
}
